info:
  description: 微服务健康和日志监控
server:
  port: 7020
spring:
  application:
    name: doyd-bootadmin
  security:
    user:
      name: zhouzq
      password: 825116
management:
  server:
    port: 50020
    servlet:
      context-path: '/c6de42bb-6078-447e-826c-773d6fd7d2da'
  endpoints:
    web:
      exposure:
        include: "*"
    endpoint:
      health:
        show-details: ALWAYS
  endpoint:
    logfile:
      external-file: /doyd-cloud/logs/doyd-boot-admin.log
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 192.168.1.3
#    ip-address: 192.168.4.110
    instance-id: ${eureka.instance.ip-address}:${server.port}
    metadata-map:
      management:
        port: ${management.server.port}
        context-path: ${management.server.servlet.context-path}/actuator
  client:
    eureka-service-url-poll-interval-seconds: 60
    registry-fetch-interval-seconds: 15
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
logging:
  file: doyd-boot-admin