server:
  port: 8768
spring:
  application:
    name: doyd-configserver-server
  profiles:
    active: default,native
  cloud:
    config:
      server:
        prefix: /appconfig
        native:
          search-locations: file:${doyd.yml.repo-dir}/{application}
          add-label-locations: false
management:
  # 修改spring boot actuator的端口和路径来提高攻击成本, 一定程度上提高安全性
  server:
    port: 50868
    servlet:
      context-path: '/86120d49-edb6-4a6a-ae93-f4ac7b12a1e8'
  endpoints:
    web:
      exposure:
        include: "*"
    endpoint:
      health:
        show-details: ALWAYS
  endpoint:
    logfile:
      external-file: /doyd-cloud/logs/doyd-config-server.log
eureka:
  instance:
    prefer-ip-address: true
#    ip-address: 127.0.0.1
#    ip-address: 192.168.4.110
    ip-address: 192.168.100.4
    instance-id: ${eureka.instance.ip-address}:${server.port}
    metadata-map:
      management:
        port: ${management.server.port}
        context-path: ${management.server.servlet.context-path}/actuator
  client:
    # 客户端从Eureka Server集群里更新Eureka Server信息的频率
    eureka-service-url-poll-interval-seconds: 60
    # 定义从注册中心获取注册服务的信息
    registry-fetch-interval-seconds: 15
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
doyd:
  yml:
    repo-dir: ./config/configserver-repo
    backup-dir: ./config/configserver-backup
logging:
  file: doyd-config-server