zipkin:
  storage:
    mysql:
      db: zipkin
      host: 39.100.105.67
      port: 3306
      use-ssl: false
      username: root
      password: 19931121@Zzq
      max-active: 5
  collector:
    rabbitmq:
      addresses: 39.100.105.67:5672
      password: zhouzq
      username: 825116