zipkin:
  storage:
    mysql:
      host: 39.100.105.67
      port: 3306
      username: root
      password: 825116
      db: zipkin
      max-active: 5
      character-encoding: utf8
      use-ssl: false
  collector:
    rabbitmq:
      queue: zipkin
      addresses: 39.100.105.67:5672
      password: guest
      username: guest