spring:
  rabbitmq:
    host: 39.100.105.67
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      routes:
        - id: config_server
          uri: lb://doyd-config-server
          predicates:
            - Path=/config-server/admin/**