spring:
  rabbitmq:
    host: 39.100.105.67
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://doyd-zipkin-server/zipkin
    zipkin:
      rabbitmq:
        queue: zipkin
      message-timeout: 3
  cloud:
    gateway:
      routes:
        - id: config_server
          uri: lb://doyd-config-server
          predicates:
            - Path=/config-server/admin/**
    discovery:
      enabled: true