spring:
  rabbitmq:
    host: 39.100.105.67
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      routes:
        - id:
          uri: lb://serviceId
          predicates:
            - Path=/demo/**
    discovery:
      enabled: true